### PR TITLE
0.15

### PR DESCRIPTION
**Pull request by agourlay**
```
cats   0.9.0 -> 1.0.1
circe  0.8.0 -> 0.9.0
http4s 0.17.6 -> 0.18.0-M8
monix  2.3.1 -> 3.0.0-M3
```
plus various performance improvements

### CODE REVIEW

**Comment by coutoPL** [comment]
Thanks a lot for this change. Can't wait to see it merged 👍

**Comment by agourlay** [comment]
@coutoPL I initially wanted to wait for all those dependencies to reach at least a `ReleaseCandidate` level before cutting the release but I am afraid it will take a while.

I have tried personally this branch on my codebase and it worked fine. 

Maybe you could also give a try to `0.15.0-SNAPSHOT` available on Maven, if everything is fine, I'll cut the release next week.

WDYT?

**Comment by coutoPL** [comment]
ok, will check snapshot and let you know how it works in my codebase. Thanks

**Comment by coutoPL** [comment]
Hi. In my project, everything seems to work fine :)

**Comment by coutoPL** [comment]
Hi @agourlay. I'd like to ask, if you could remove akka-stream dependency from dependencies list of your project? You are using akka-http which uses akka-streams 2.4.20. I've tried to remove it and compile and it seems that it is redundant. 

In my codebase at the moment I have to exclude it.

**Comment by agourlay** [comment]
The problem is that the next version of akka-http will not pull akka-stream anymore.

see https://akka.io/blog/news/2017/12/22/akka-http-10.1.0-RC1-released

```
Using Akka HTTP with Akka 2.5 used to be a bit confusing, because Akka HTTP explicitly
 depended on Akka 2.4. Trying to use it together with Akka 2.5, running an Akka HTTP 
application could fail with class loading issues if you forgot to add a dependency to both 
akka-actor and akka-stream of the same version. For that reason, we changed the policy 
not to depend on akka-stream explicitly any more but mark it as a provided dependency 
in our build. That means that you will have to always add a manual dependency to akka-stream. 
Please make sure you have chosen and added a dependency to akka-stream when updating to 
the new version. (Veterans may remember this policy from spray.)
```

The long term goal of Cornichon is to remove completely the akka-http dependency to avoid classpath issues. Morevover, I recommend in general to not share the classpath of Cornichon with the application under test.

What is your current setup exactly?

**Comment by coutoPL** [comment]
I'm using akka-http 10.0.11 and when I allow to evict akka-streams 2.4.20  by 2.5.X, at runtime I get `ClassNotFoundException` for akka-http internals (AFAIR). Excluding 2.5.X solves the problem.

I understand that when you switch to akka-http 10.1.0, you will have to explicitly define akka-streams in your dependencies, but at the moment it is not needed.

**Comment by agourlay** [comment]
here we go https://github.com/agourlay/cornichon/commit/e3ee0625fba463653750ad53cac6c83184fb2b40

Now let's release that 0.15 😺

**Comment by agourlay** [comment]
Artifacts pushed, currently syncing to Maven.

**Pull request merged**
