### PR TITLE
First pass at formData support on HttpRequest

### PR DESCRIPTION
**Pull request by drising-mfp**
This is a very basic implementation of the first option mentioned on #112 (addition of formData separate from payload). It still needs to be fleshed out and tested but the general shape is there for discussion.

### CODE REVIEW

**Comment by agourlay** [comment]
Thank you for the contribution, I will review this in details on Monday 👍

**Comment by agourlay** [comment]
I had a first look and as you said it yourself in the issue, I am not super convinced by this approach either.

Before digging deeper into that solution, I would like to know how urgent is this feature for you?

I thought a bit about this issue and I might try to work on a generalized solution for any payload type but this obviously not be released tomorrow.

**Comment by drising-mfp** [comment]
Yes, I agree that a generalized solution would be a better way to go. This is little more than a hack.

This feature is not at all urgent for me. Take your time.

I may also play around with it some but can't really commit to making any meaningful progress. But if I do and I feel like I have something new worth looking at I'll open another PR here.

**Comment by agourlay** [comment]
Closing this PR as I have an idea for a generalized solution. No ETA :)

**Pull request closed without merging**
