### PR TITLE
Type 2, get 3rd free :clown_face:

### PR DESCRIPTION
**Pull request by cneijenhuis**

### CODE REVIEW

**Comment by agourlay** [comment]
👓

**Comment by OlegIlyenko** [comment]
@agourlay btw, I was wondering, why are you using triple back-tick for inline code fragments. Is there any benefit in comparison to a single back-tick?

**Comment by agourlay** [comment]
TBH it is mostly a copy paste from the former readme file where I was leveraging the syntax highlighting offered by the Github's MD https://guides.github.com/features/mastering-markdown/

**Comment by OlegIlyenko** [comment]
Ok, thx! Looks like this tutorial also uses single back-tick:

> Inline code
>
> I think you should use an
> `<addr>` element here instead.

I was actually surprised that triple back-tick works inline as well

**Pull request merged**
